all:
	./compileKeyboard.rb keyboard-us.json ../BasiliskII/Keyboard\ Layouts/US.nfkeyboardlayout
	./compileKeyboard.rb keyboard-uk.json ../BasiliskII/Keyboard\ Layouts/British.nfkeyboardlayout
	./compileKeyboard.rb keyboard-es.json ../BasiliskII/Keyboard\ Layouts/Spanish\ \(ISO\).nfkeyboardlayout
	./compileKeyboard.rb keyboard-es-traditional.json ../BasiliskII/Keyboard\ Layouts/Spanish.nfkeyboardlayout
	./compileKeyboard.rb keyboard-fr.json ../BasiliskII/Keyboard\ Layouts/French.nfkeyboardlayout
